FROM python:3.10

WORKDIR /app

RUN pip install mlflow boto3

# Copy the rest of the application source code
COPY . .

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db"]
